apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - db-secret.yaml
    - db.yaml
    - repository.yaml
    - release.yaml
    - sops-secret-store.yaml
    - sops-age.yaml
namespace: external-secrets
