apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 10m
  releaseName: harbor
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor-repo
  values:
    installCRDs: true