---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    selfhost.security: sops
  name: &app servarr
  namespace: &namespace servarr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/servarr/deployment
  targetNamespace: *namespace
  prune: true
  timeout: 30m0s