apiVersion: v1
stringData:
    netbird-relay-secret-key: ENC[AES256_GCM,data:krdfmAx4zM4sF5d5lggHyRXw9wV7eBIPzbMQYdSkQLUkLMUQqRyLiZ1f6A==,iv:Z8q0vsOnIjsHkBNE8xEhQ8PknCW0tJSo3uUlOV4i2LQ=,tag:uQcT/sMAIHcWFs2nJSY5Tg==,type:str]
kind: Secret
metadata:
    name: netbird-relay-secret
    namespace: netbird
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVkJiSVBHUWlmd0Q1NGZ4
            dis4bmNxejNxMDdOa0FpQ3h3OURVeG8vTkJnCktOTDMxWGNyZ0sxZkJSd05Kb1Iw
            MTNCbWxlYVBQWVhveTZrS3lRbzhVbEEKLS0tIHZmRUFQM21uOTF5Q0dTYVczZlNI
            QVo0VXMwTDFiYkU3eVE3bWlpck1ZSjQKymmSNoZQdihw7UKrHplJ9zYtrx14dFdZ
            Vcel4p4I2NT1y5+C17IfSdAHS+42fQuYwFt9JWmFvFOwe/eWI03YfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:48:28Z"
    mac: ENC[AES256_GCM,data:AEMhXYbMyqMspppQL/cxstzs5JmF5wvm4mJeEmjBmsYxCmpPHMNx0gjdaU/0P2rcnOD5Y9nZ1egtd/JfYhkVUWlXqT++b1Z4SqfNgzAL9brvlznfzt7S54XWYNJrtm6f4dbY4lm6o7SemAgguxzCKoqac59ReRWZwLLYDgOYHvc=,iv:5s5x9vfVPAo4ChszsJDZ+EI5SsuXRj4f1/WUjz27Bws=,tag:H8aD1wyZK+UO/73s3z/Eew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
