apiVersion: v1
stringData:
    netbird-relay-secret-key: ENC[AES256_GCM,data:ACQePxxpatRz7SHOoqiN01nABF31IcWXe761B2dDDfcZol3m9Gj6vfZxcA==,iv:mvazoVaw+hNbFwSojzUnCq+MV6lXN4Ev78oxSdJqg/s=,tag:8hxFw6bRi1iVPp0uCro+Tg==,type:str]
kind: Secret
metadata:
    name: netbird-relay-secret
    namespace: netbird
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczRTR2pZUVl5Mnh1K29X
            cVd5VTBTK2d3cEpHYmNBV2xlNElaTlprNGhjCkppbnJoM0pDZ3VEVVk4RFVTMzZv
            U2dPdWdUd1B6R2ZGNnJmYkxxcG1hMEUKLS0tIDJhUjJCUy9FeDFvemc2aGlXalgw
            Vks0eGwzSTdEa3JjRzdTaXgydkt2VE0KUj/y5ijNHcuolulagcM4TgEIGVZgRH7V
            JmLaDi+o9uc2OLXqxiyzz/i2iicUwGz5GObyuy43g+/ZZIiunJtnEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T21:57:37Z"
    mac: ENC[AES256_GCM,data:UlpviLkKhXBmTLDT21Lq5GKJ2ck9BGZ9JwQIKC8X+tIUgd2D+GXkZcocp6PksL71cv6f00yjd5+ghpfeJjSgtks6/1M2FBZnnqjmM+WToNfj02d9DnhKTqzuDhJDLRVSLX+0+LTXzOYX3irYk/nOyVtYbLdw2cuZAT08yLxvCrA=,iv:s0YO2jpntbY4wTIftKi2y3/tuuZWt0/nI/bqeKXjqEI=,tag:uf/IAUeeN1n+nlh8fGxhLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
