apiVersion: v1
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:DVGp54lr/y28LQi3T8qFiBEE3arLBqGQrrv5ayQK9POIhED1gonmFQ==,iv:9i1d7ed0zFLiPbi36ud9aUOd8b0Fja9jKjeOPH0AXPU=,tag:NWvTNUFXxUn9RE8E/E3mAg==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWKzlxVGxNRDYyMjdvd2xV
            WU1CeEYvWG82V3FnWkNUbFFxUzVvUjgycG1ZCmlZenZuNWxrVjUrejFLbk1XNzQv
            UEtwdHhBY01iSVBhdW9mMXhrSWtNTmsKLS0tIHJqT3ZXQXpvSUdIbGtTZGdqRmxT
            RzVXc0xyWi9iNi9WQytrbW5IUW5MMUkKdT+GmY+0SqxBtCtTXEpoPajxrf819SI1
            FlEFgWektuyzuAwFXjmCK4p++Djhw/1xOubbn//rjQNllSc5Ky2WXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T13:38:35Z"
    mac: ENC[AES256_GCM,data:SVeKajMw3xzcDjc5nMzp61LaQXRJkIVwXmY1T9CTGXVVq0ZLzLpILV9mTfHxGLsyXc7YLNqCNqHUS5TZkjQCFv8YHw6CTY+SyXV1Ib4VnlRucQXz+dpMNj4G/z7IX+tTS+UoLjyjKNtYixngTmy55uWsRz9jCROvHTVeqE7PDKc=,iv:X+EWDD0Kxlsg7AK9Uns3HQzxXv4d3lBw57m739Ln3dc=,tag:ahdJTeB2P6r/JoDxLdqtEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
