apiVersion: v1
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:Zx2TgucAYzeMNCyNhtpqKX27Qu1svOxrVWwu7cmYeezVbV8lodwxUA==,iv:j5rF/9r9nwU1SBb9krpRH9xcmBNPp9ieVhjFHvv8WxM=,tag:NnjejiS3DSmfeDGhHleGWA==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVhjVUlnMGtJRHU3RzA3
            cFlFTlF6UXBWTTE1R2lYSmNrTDBaa01FU1d3CitQZnpCWnpqS0NHSlFvRkl5ajBO
            MkF4YWdUOFNnZjZUTUxOWC9HRHZMb3cKLS0tIFkrZUtyaG9lN1FFOHhFWUJITk1V
            aWNGN1NwZUh2UGNsK1E3aUFkc1R4bmsKVBGXYlfmyVGTxHMngcoezXpJHlmwVuI/
            B40UldPC7BuyJZwIGMyghasD50TtrAw3AIZMMvRzyrZNTrQWr9Le6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T21:54:06Z"
    mac: ENC[AES256_GCM,data:Mcbc7dUdo/u7Bi4iimltkGQegH5MphFdqZ5P+8UeU1f2mj7vU3SrceTdjoKJrRYlz9cF4ctsYmhFXDJGfr5WmGIwzCIRLYZQssim0VfotkRWvclmSZ1KqLU7cgKw6cM9ituCevbtKLrv+GjAWHvqnqziDXWROzq6NV+OlIS80TQ=,iv:JEzxYwTk8wEQ2eUokkxEBR1f/OdX4seQj49O8vRLh3U=,tag:w4p7b4MpXJed4NyTgPn80g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
