apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-runner-deployment
  namespace: crd-ns
spec:
  template:
    spec:
      repository: mumoshu/actions-runner-controller-ci
      labels:
        - self-hosted