apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr 
resources:
  - resources/talos-media-volume.yaml
  #- resources/servarr-ing-external.yaml
  - regcred.yaml 
  - repository.yaml
  - components/qbittorrent.yaml
  - components/lidarr.yaml
  - components/radarr.yaml
  - components/sonarr.yaml
  - components/jellyfin.yaml
  - components/audiobookshelf.yaml
  - components/prowlarr.yaml
  - components/flaresolverr.yaml
  - components/jellyseerr.yaml
  - components/bazarr.yaml
