---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    selfhost.security: sops
  name: &app github-actions
  namespace: &namespace crd-ns
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: github-runner
      namespace: *namespace
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/infrastructure/crds/github-action-operator/app
  targetNamespace: *namespace
  prune: true
  timeout: 5m0s