apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crd-ns
resources:
  - namespace.yaml
  - psql-operator/repository.yaml
  - psql-operator/release.yaml
  - github-action-operator/ks-base.yaml
  - github-action-operator/ks-runners.yaml
